sonar.projectKey=millsks_conventional-commit-hook
sonar.organization=millsks
sonar.projectName=conventional-commit-hook
sonar.projectVersion=0.1.0

sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.ruff.reportPaths=ruff-report.json

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/tests/**,**/__pycache__/**,**/.*/**,htmlcov/**,**/*.pyc
sonar.test.exclusions=**/tests/**
sonar.coverage.exclusions=**/tests/**,**/__pycache__/**

sonar.python.version=3.10,3.11,3.12,3.13
